services:
  - type: web
    name: artisan-marketplace-backend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_PEPPER
        generateValue: true
      - key: CLIENT_URL
        sync: false
      - key: SERVER_URL
        fromService:
          type: web
          name: artisan-marketplace-backend
          property: host
